name: Release KOCity Launcher Wrapper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Make a folder
        run: mkdir -p KOCity

      - name: Download AppImage
        run: |
          wget -O KOCity/knockoutcitylauncher-2.0.3.AppImage https://github.com/kocxyz/Launcher/releases/download/v2.0.3/knockoutcitylauncher-2.0.3.AppImage
          chmod +x KOCity/knockoutcitylauncher-2.0.3.AppImage

      - name: Copy files to KOCity folder
        run: |
          cp knockoutcitylauncher.sh KOCity/
          cp wine KOCity/
          chmod +x KOCity/knockoutcitylauncher.sh
          chmod +x KOCity/wine
          cp -Rv ULWGL-launcher KOCity/
          rm -rf KOCity/ULWGL-launcher/.git

      - name: Compress into tar archive
        run: tar -cvf KOCity.tar KOCity

      - name: Get version from file and create environment file
        run: |
          echo "version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          name: Release v${{ env.version }}
          draft: false
          prerelease: false
          files: ./KOCity.tar
